project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx:
    fig-cap-location: top
    fig-align: center
    fig-format: png
    tbl-cap-location: top
    reference-doc: custom-reference.docx
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



