project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    notebook: false
    notebook-source: false
    comments:
      hypothesis: true

  docx:
    notebook: false
    notebook-source: false
    fig-cap-location: top
    fig-align: center
    fig-format: png
    tbl-cap-location: top
    reference-doc: custom-reference.docx

  jats: default

execute:
  freeze: true




